const exercisePool = [
    // Chest
  { name: 'Assisted Dip', muscles: ['chest', 'triceps', 'shoulders'] },
  { name: 'Band-Assisted Bench Press', muscles: ['chest', 'triceps', 'shoulders'] },
  { name: 'Bar Dip', muscles: ['chest', 'triceps', 'shoulders'] },
  { name: 'Bench Press', muscles: ['chest', 'triceps', 'shoulders'] },
  { name: 'Bench Press Against Band', muscles: ['chest', 'triceps', 'shoulders'] },
  { name: 'Board Press', muscles: ['chest', 'triceps'] },
  { name: 'Cable Chest Press', muscles: ['chest', 'triceps'] },
  { name: 'Close-Grip Bench Press', muscles: ['triceps', 'chest'] },
  { name: 'Close-Grip Feet-Up Bench Press', muscles: ['triceps', 'chest'] },
  { name: 'Decline Bench Press', muscles: ['chest', 'triceps'] },
  { name: 'Decline Push-Up', muscles: ['chest', 'triceps'] },
  { name: 'Dumbbell Chest Fly', muscles: ['chest'] },
  { name: 'Dumbbell Chest Press', muscles: ['chest', 'triceps'] },
  { name: 'Dumbbell Decline Chest Press', muscles: ['chest', 'triceps'] },
  { name: 'Dumbbell Floor Press', muscles: ['chest', 'triceps'] },
  { name: 'Dumbbell Pullover', muscles: ['chest', 'lats'] },
  { name: 'Feet-Up Bench Press', muscles: ['chest', 'triceps'] },
  { name: 'Floor Press', muscles: ['chest', 'triceps'] },
  { name: 'Incline Bench Press', muscles: ['chest', 'shoulders', 'triceps'] },
  { name: 'Incline Dumbbell Press', muscles: ['chest', 'shoulders', 'triceps'] },
  { name: 'Incline Push-Up', muscles: ['chest', 'triceps'] },
  { name: 'Kettlebell Floor Press', muscles: ['chest', 'triceps'] },
  { name: 'Kneeling Incline Push-Up', muscles: ['chest', 'triceps'] },
  { name: 'Kneeling Push-Up', muscles: ['chest', 'triceps'] },
  { name: 'Machine Chest Fly', muscles: ['chest'] },
  { name: 'Machine Chest Press', muscles: ['chest', 'triceps'] },
  { name: 'Pec Deck', muscles: ['chest'] },
  { name: 'Pin Bench Press', muscles: ['chest', 'triceps'] },
  { name: 'Push-Up', muscles: ['chest', 'triceps', 'shoulders'] },
  { name: 'Push-Up Against Wall', muscles: ['chest', 'triceps'] },
  { name: 'Push-Ups With Feet in Rings', muscles: ['chest', 'triceps', 'shoulders'] },
  { name: 'Resistance Band Chest Fly', muscles: ['chest'] },
  { name: 'Ring Dip', muscles: ['chest', 'triceps', 'shoulders'] },
  { name: 'Smith Machine Bench Press', muscles: ['chest', 'triceps'] },
  { name: 'Smith Machine Incline Bench Press', muscles: ['chest', 'shoulders', 'triceps'] },
  { name: 'Smith Machine Reverse Grip Bench Press', muscles: ['chest', 'triceps', 'biceps'] },
  { name: 'Standing Cable Chest Fly', muscles: ['chest'] },
  { name: 'Standing Resistance Band Chest Fly', muscles: ['chest'] },
  // Shoulders
{ name: 'Arnold Press', muscles: ['shoulders', 'triceps'] },
{ name: 'Band Pull-Apart', muscles: ['shoulders', 'rear_delts', 'upper_back'] },
{ name: 'Banded Face Pull', muscles: ['rear_delts', 'shoulders', 'traps'] },
{ name: 'Barbell Front Raise', muscles: ['front_delts'] },
{ name: 'Barbell Rear Delt Row', muscles: ['rear_delts', 'back'] },
{ name: 'Barbell Upright Row', muscles: ['shoulders', 'traps'] },
{ name: 'Behind the Neck Press', muscles: ['shoulders', 'triceps'] },
{ name: 'Cable Front Raise', muscles: ['front_delts'] },
{ name: 'Cable Lateral Raise', muscles: ['side_delts'] },
{ name: 'Cable Rear Delt Row', muscles: ['rear_delts', 'shoulders'] },
{ name: 'Devils Press', muscles: ['shoulders', 'chest', 'triceps'] },
{ name: 'Dumbbell Front Raise', muscles: ['front_delts'] },
{ name: 'Dumbbell Lateral Raise', muscles: ['side_delts'] },
{ name: 'Dumbbell Rear Delt Row', muscles: ['rear_delts', 'shoulders'] },
{ name: 'Dumbbell Shoulder Press', muscles: ['shoulders', 'triceps'] },
{ name: 'Face Pull', muscles: ['rear_delts', 'shoulders', 'traps'] },
{ name: 'Front Hold', muscles: ['front_delts'] },
{ name: 'Landmine Press', muscles: ['shoulders', 'triceps'] },
{ name: 'Machine Lateral Raise', muscles: ['side_delts'] },
{ name: 'Machine Shoulder Press', muscles: ['shoulders', 'triceps'] },
{ name: 'Monkey Row', muscles: ['shoulders', 'traps'] },
{ name: 'One-Arm Landmine Press', muscles: ['shoulders', 'triceps'] },
{ name: 'Overhead Press', muscles: ['shoulders', 'triceps'] },
{ name: 'Plate Front Raise', muscles: ['front_delts'] },
{ name: 'Push Press', muscles: ['shoulders', 'triceps', 'quads'] },
{ name: 'Reverse Cable Flyes', muscles: ['rear_delts'] },
{ name: 'Reverse Dumbbell Flyes', muscles: ['rear_delts'] },
{ name: 'Reverse Machine Fly', muscles: ['rear_delts'] },
{ name: 'Seated Dumbbell Shoulder Press', muscles: ['shoulders', 'triceps'] },
{ name: 'Seated Barbell Overhead Press', muscles: ['shoulders', 'triceps'] },
{ name: 'Seated Smith Machine Shoulder Press', muscles: ['shoulders', 'triceps'] },
{ name: 'Snatch Grip Behind the Neck Press', muscles: ['shoulders', 'triceps'] },
{ name: 'Squat Jerk', muscles: ['shoulders', 'triceps', 'quads', 'hamstrings'] },
{ name: 'Split Jerk', muscles: ['shoulders', 'triceps', 'quads', 'hamstrings'] },

// Triceps
{ name: 'Barbell Standing Triceps Extension', muscles: ['triceps'] },
{ name: 'Barbell Incline Triceps Extension', muscles: ['triceps'] },
{ name: 'Barbell Lying Triceps Extension', muscles: ['triceps'] },
{ name: 'Bench Dip', muscles: ['triceps', 'chest', 'shoulders'] },
{ name: 'Crossbody Cable Triceps Extension', muscles: ['triceps'] },
{ name: 'Close-Grip Push-Up', muscles: ['triceps', 'chest'] },
{ name: 'Dumbbell Lying Triceps Extension', muscles: ['triceps'] },
{ name: 'Dumbbell Standing Triceps Extension', muscles: ['triceps'] },
{ name: 'Overhead Cable Triceps Extension', muscles: ['triceps'] },
{ name: 'Tate Press', muscles: ['triceps'] },
{ name: 'Tricep Bodyweight Extension', muscles: ['triceps'] },
{ name: 'Tricep Pushdown With Bar', muscles: ['triceps'] },
{ name: 'Tricep Pushdown With Rope', muscles: ['triceps'] },

// Legs
{ name: 'Air Squat', muscles: ['quads', 'glutes'] },
{ name: 'Barbell Hack Squat', muscles: ['quads', 'glutes'] },
{ name: 'Barbell Lunge', muscles: ['quads', 'glutes', 'hamstrings'] },
{ name: 'Barbell Walking Lunge', muscles: ['quads', 'glutes', 'hamstrings'] },
{ name: 'Belt Squat', muscles: ['quads', 'glutes'] },
{ name: 'Body Weight Lunge', muscles: ['quads', 'glutes', 'hamstrings'] },
{ name: 'Bodyweight Leg Curl', muscles: ['hamstrings', 'glutes'] },
{ name: 'Box Jump', muscles: ['quads', 'glutes', 'calves'] },
{ name: 'Box Squat', muscles: ['quads', 'glutes'] },
{ name: 'Bulgarian Split Squat', muscles: ['quads', 'glutes', 'hamstrings'] },
{ name: 'Chair Squat', muscles: ['quads', 'glutes'] },
{ name: 'Dumbbell Lunge', muscles: ['quads', 'glutes', 'hamstrings'] },
{ name: 'Dumbbell Squat', muscles: ['quads', 'glutes'] },
{ name: 'Front Squat', muscles: ['quads', 'glutes', 'core'] },
{ name: 'Glute Ham Raise', muscles: ['hamstrings', 'glutes'] },
{ name: 'Goblet Squat', muscles: ['quads', 'glutes'] },
{ name: 'Hack Squat Machine', muscles: ['quads', 'glutes'] },
{ name: 'Half Air Squat', muscles: ['quads'] },
{ name: 'Hip Adduction Machine', muscles: ['adductors'] },
{ name: 'Jumping Lunge', muscles: ['quads', 'glutes', 'hamstrings', 'calves'] },
{ name: 'Landmine Hack Squat', muscles: ['quads', 'glutes'] },
{ name: 'Landmine Squat', muscles: ['quads', 'glutes'] },

{ name: 'Leg Curl On Ball', muscles: ['hamstrings', 'glutes'] },
{ name: 'Leg Extension', muscles: ['quads'] },
{ name: 'Leg Press', muscles: ['quads', 'glutes', 'hamstrings'] },
{ name: 'Lying Leg Curl', muscles: ['hamstrings'] },
{ name: 'Nordic Hamstring Eccentric', muscles: ['hamstrings'] },
{ name: 'One-Legged Leg Extension', muscles: ['quads'] },
{ name: 'One-Legged Lying Leg Curl', muscles: ['hamstrings'] },
{ name: 'One-Legged Seated Leg Curl', muscles: ['hamstrings'] },
{ name: 'Pause Squat', muscles: ['quads', 'glutes'] },
{ name: 'Pistol Squat', muscles: ['quads', 'glutes', 'hamstrings', 'core'] },
{ name: 'Reverse Barbell Lunge', muscles: ['quads', 'glutes', 'hamstrings'] },
{ name: 'Reverse Body Weight Lunge', muscles: ['quads', 'glutes', 'hamstrings'] },
{ name: 'Reverse Dumbbell Lunge', muscles: ['quads', 'glutes', 'hamstrings'] },
{ name: 'Romanian Deadlift', muscles: ['hamstrings', 'glutes', 'lower_back'] },
{ name: 'Safety Bar Squat', muscles: ['quads', 'glutes'] },
{ name: 'Seated Leg Curl', muscles: ['hamstrings'] },
{ name: 'Shallow Body Weight Lunge', muscles: ['quads'] },
{ name: 'Side Lunges (Bodyweight)', muscles: ['quads', 'glutes', 'adductors'] },
{ name: 'Smith Machine Bulgarian Split Squat', muscles: ['quads', 'glutes', 'hamstrings'] },
{ name: 'Smith Machine Front Squat', muscles: ['quads', 'glutes'] },
{ name: 'Smith Machine Squat', muscles: ['quads', 'glutes'] },
{ name: 'Squat', muscles: ['quads', 'glutes', 'hamstrings'] },
{ name: 'Step Up', muscles: ['quads', 'glutes', 'hamstrings'] },
{ name: 'Zercher Squat', muscles: ['quads', 'glutes', 'core'] },
{ name: 'Zombie Squat', muscles: ['quads', 'glutes', 'core'] },

// Back
{ name: 'Assisted Chin-Up', muscles: ['back', 'lats', 'biceps'] },
{ name: 'Assisted Pull-Up', muscles: ['back', 'lats', 'biceps'] },
{ name: 'Back Extension', muscles: ['lower_back', 'glutes'] },
{ name: 'Banded Muscle-Up', muscles: ['back', 'lats', 'biceps', 'shoulders'] },
{ name: 'Barbell Row', muscles: ['back', 'lats', 'biceps'] },
{ name: 'Barbell Shrug', muscles: ['traps'] },
{ name: 'Block Clean', muscles: ['back', 'traps', 'hamstrings'] },
{ name: 'Block Snatch', muscles: ['back', 'traps', 'hamstrings'] },
{ name: 'Cable Close Grip Seated Row', muscles: ['back', 'lats', 'biceps'] },
{ name: 'Cable Wide Grip Seated Row', muscles: ['back', 'lats', 'biceps'] },
{ name: 'Chest to Bar', muscles: ['back', 'lats', 'biceps'] },
{ name: 'Chin-Up', muscles: ['back', 'lats', 'biceps'] },
{ name: 'Clean', muscles: ['back', 'traps', 'glutes', 'hamstrings'] },
{ name: 'Clean and Jerk', muscles: ['back', 'traps', 'quads', 'hamstrings', 'shoulders'] },
{ name: 'Close-Grip Lat Pulldown', muscles: ['back', 'lats', 'biceps'] },
{ name: 'Deadlift', muscles: ['back', 'glutes', 'hamstrings'] },
{ name: 'Deficit Deadlift', muscles: ['back', 'glutes', 'hamstrings'] },
{ name: 'Dumbbell Deadlift', muscles: ['back', 'glutes', 'hamstrings'] },
{ name: 'Dumbbell Row', muscles: ['back', 'lats', 'biceps'] },
{ name: 'Dumbbell Shrug', muscles: ['traps'] },

{ name: 'Floor Back Extension', muscles: ['lower_back', 'glutes'] },
{ name: 'Good Morning', muscles: ['lower_back', 'hamstrings', 'glutes'] },
{ name: 'Gorilla Row', muscles: ['back', 'lats', 'biceps'] },
{ name: 'Hang Clean', muscles: ['back', 'traps', 'hamstrings'] },
{ name: 'Hang Power Clean', muscles: ['back', 'traps', 'hamstrings'] },
{ name: 'Hang Power Snatch', muscles: ['back', 'traps', 'hamstrings'] },
{ name: 'Hang Snatch', muscles: ['back', 'traps', 'hamstrings'] },
{ name: 'Inverted Row', muscles: ['back', 'lats', 'biceps'] },
{ name: 'Inverted Row with Underhand Grip', muscles: ['back', 'lats', 'biceps'] },
{ name: 'Jefferson Curl', muscles: ['lower_back', 'hamstrings'] },
{ name: 'Jumping Muscle-Up', muscles: ['back', 'lats', 'biceps', 'shoulders'] },
{ name: 'Kettlebell Clean', muscles: ['back', 'traps'] },
{ name: 'Kettlebell Clean & Jerk', muscles: ['back', 'traps', 'shoulders'] },
{ name: 'Kettlebell Clean & Press', muscles: ['back', 'traps', 'shoulders'] },
{ name: 'Kettlebell Swing', muscles: ['back', 'glutes', 'hamstrings'] },
{ name: 'Kroc Row', muscles: ['back', 'lats', 'biceps'] },
{ name: 'Lat Pulldown With Pronated Grip', muscles: ['back', 'lats', 'biceps'] },
{ name: 'Lat Pulldown With Supinated Grip', muscles: ['back', 'lats', 'biceps'] },
{ name: 'Muscle-Up (Bar)', muscles: ['back', 'lats', 'biceps', 'shoulders'] },
{ name: 'Muscle-Up (Rings)', muscles: ['back', 'lats', 'biceps', 'shoulders'] },
{ name: 'Neutral Close-Grip Lat Pulldown', muscles: ['back', 'lats', 'biceps'] },
{ name: 'One-Handed Cable Row', muscles: ['back', 'lats', 'biceps'] },
{ name: 'One-Handed Kettlebell Swing', muscles: ['back', 'glutes', 'hamstrings'] },

{ name: 'One-Handed Lat Pulldown', muscles: ['back', 'lats', 'biceps'] },
{ name: 'Pause Deadlift', muscles: ['back', 'glutes', 'hamstrings'] },
{ name: 'Pendlay Row', muscles: ['back', 'lats', 'biceps'] },
{ name: 'Power Clean', muscles: ['back', 'traps', 'glutes'] },
{ name: 'Power Snatch', muscles: ['back', 'traps', 'glutes'] },
{ name: 'Pull-Up', muscles: ['back', 'lats', 'biceps'] },
{ name: 'Pull-Up With a Neutral Grip', muscles: ['back', 'lats', 'biceps'] },
{ name: 'Rack Pull', muscles: ['back', 'glutes', 'hamstrings'] },
{ name: 'Ring Pull-Up', muscles: ['back', 'lats', 'biceps'] },
{ name: 'Ring Row', muscles: ['back', 'lats', 'biceps'] },
{ name: 'Scap Pull-Up', muscles: ['traps', 'shoulders'] },
{ name: 'Seal Row', muscles: ['back', 'lats', 'biceps'] },
{ name: 'Seated Machine Row', muscles: ['back', 'lats', 'biceps'] },
{ name: 'Single Leg Deadlift with Kettlebell', muscles: ['hamstrings', 'glutes', 'lower_back'] },
{ name: 'Smith Machine One-Handed Row', muscles: ['back', 'lats'] },
{ name: 'Snatch', muscles: ['back', 'traps', 'glutes'] },
{ name: 'Snatch Grip Deadlift', muscles: ['back', 'glutes', 'hamstrings'] },
{ name: 'Stiff-Legged Deadlift', muscles: ['hamstrings', 'glutes', 'lower_back'] },
{ name: 'Straight Arm Lat Pulldown', muscles: ['lats', 'back'] },
{ name: 'Sumo Deadlift', muscles: ['glutes', 'hamstrings', 'back'] },
{ name: 'T-Bar Row', muscles: ['back', 'lats', 'biceps'] },
{ name: 'Towel Row', muscles: ['back', 'lats', 'biceps'] },
{ name: 'Trap Bar Deadlift With High Handles', muscles: ['glutes', 'hamstrings', 'back'] },
{ name: 'Trap Bar Deadlift With Low Handles', muscles: ['glutes', 'hamstrings', 'back'] },


// Abs / Core
{ name: 'Ball Slams', muscles: ['core', 'abs'] },
{ name: 'Cable Crunch', muscles: ['abs'] },
{ name: 'Core Twist', muscles: ['obliques', 'abs'] },
{ name: 'Crunch', muscles: ['abs'] },
{ name: 'Dead Bug', muscles: ['core', 'abs'] },
{ name: 'Dead Bug With Dumbbells', muscles: ['core', 'abs'] },
{ name: 'Dragon Flag', muscles: ['abs', 'core'] },
{ name: 'Hanging Knee Raise', muscles: ['abs', 'hip_flexors'] },
{ name: 'Hanging Leg Raise', muscles: ['abs', 'hip_flexors'] },
{ name: 'Hanging Sit-Up', muscles: ['abs'] },
{ name: 'Hanging Windshield Wiper', muscles: ['obliques', 'abs'] },
{ name: 'High to Low Wood Chop with Band', muscles: ['obliques', 'core'] },
{ name: 'High to Low Wood Chop with Cable', muscles: ['obliques', 'core'] },
{ name: 'Hollow Hold', muscles: ['core'] },
{ name: 'Horizontal Wood Chop with Band', muscles: ['obliques', 'core'] },
{ name: 'Horizontal Wood Chop with Cable', muscles: ['obliques', 'core'] },
{ name: 'Jackknife Sit-Up', muscles: ['abs'] },
{ name: 'Kettlebell Plank Pull Through', muscles: ['core', 'shoulders'] },
{ name: 'Kneeling Ab Wheel Roll-Out', muscles: ['abs', 'core'] },
{ name: 'Kneeling Plank', muscles: ['core'] },
{ name: 'Kneeling Side Plank', muscles: ['obliques', 'core'] },
{ name: 'L-Sit', muscles: ['abs', 'hip_flexors'] },
{ name: 'Lying Leg Raise', muscles: ['abs'] },
{ name: 'Lying Windshield Wiper', muscles: ['obliques', 'abs'] },
{ name: 'Lying Windshield Wiper with Bent Knees', muscles: ['obliques', 'abs'] },
{ name: 'Machine Crunch', muscles: ['abs'] },
{ name: 'Mountain Climbers', muscles: ['core', 'abs'] },
{ name: 'Oblique Crunch', muscles: ['obliques'] },
{ name: 'Oblique Sit-Up', muscles: ['obliques', 'abs'] },
{ name: 'Plank', muscles: ['core'] },
{ name: 'Plank with Leg Lifts', muscles: ['core', 'glutes'] },
{ name: 'Side Plank', muscles: ['obliques', 'core'] },
{ name: 'Sit-Up', muscles: ['abs'] },


// Calves
{ name: 'Barbell Standing Calf Raise', muscles: ['calves'] },
{ name: 'Donkey Calf Raise', muscles: ['calves'] },
{ name: 'Eccentric Heel Drop', muscles: ['calves'] },
{ name: 'Heel Raise', muscles: ['calves'] },
{ name: 'Seated Calf Raise', muscles: ['calves'] },
{ name: 'Standing Calf Raise', muscles: ['calves'] }
];
